#!/usr/bin/env sh
#
# Build the change-log static site (no Jekyll -- avoids GitHub-coupled themes).
# Converts every *.md in this repo into public/<path>.html with one clean
# template, rewriting inter-page links (.md / extension-less CHANGELOG -> .html).
# The markdown itself is generated by each repo's CI `changelog` job.

set -eu

OUT=public
rm -rf "$OUT"; mkdir -p "$OUT"

# Markdown -> HTML. marked keeps raw HTML (our <a id> anchors) and GFM tables.
npm install -g marked@12 >/dev/null 2>&1

CSS='<style>
:root{color-scheme:light}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#1f2328;margin:0;background:#fff;line-height:1.5}
.wrap{max-width:1012px;margin:0 auto;padding:0 32px 64px}
header.site{border-bottom:1px solid #d0d7de;padding:16px 0;margin-bottom:24px;display:flex;gap:16px;align-items:center}
header.site .t{font-weight:600;font-size:16px}
header.site a{color:#0969da;text-decoration:none}
h1,h2{border-bottom:1px solid #d8dee4;padding-bottom:.3em}
h1{font-size:2em;margin:.67em 0}h2{margin-top:28px;font-size:1.5em}h3{font-size:1.15em}
table{border-collapse:collapse;margin:12px 0;display:block;overflow:auto}
th,td{border:1px solid #d0d7de;padding:6px 13px}th{background:#f6f8fa}tr:nth-child(2n) td{background:#f6f8fa}
code{background:#eff1f3;padding:.2em .4em;border-radius:6px;font-size:85%}
a{color:#0969da;text-decoration:none}a:hover{text-decoration:underline}
ul{padding-left:2em}li{margin:.2em 0}
hr{height:1px;background:#d0d7de;border:0;margin:24px 0}
</style>'

# List every markdown file (skip build output / vcs / node_modules).
find . -type f -name '*.md' \
  -not -path './public/*' -not -path './node_modules/*' -not -path './.git/*' \
  | sed 's#^\./##' | sort > /tmp/mdlist

while IFS= read -r md; do
  [ -n "$md" ] || continue
  rel="${md%.md}"
  out="$OUT/${rel}.html"
  mkdir -p "$(dirname "$out")"

  # depth = number of '/' in rel -> "../" prefix so the Home link resolves.
  depth=$(printf '%s' "$rel" | awk -F/ '{print NF-1}')
  root=""; i=0; while [ "$i" -lt "$depth" ]; do root="../$root"; i=$((i+1)); done

  # strip any leading Jekyll front matter; rewrite links to .html.
  awk 'NR==1&&/^---$/{f=1;next} f&&/^---$/{f=0;next}{print}' "$md" \
    | sed -E 's#\]\(([^)]*/CHANGELOG)\)#](\1.html)#g; s#\]\(([^)]*)\.md\)#](\1.html)#g' > /tmp/body.md
  marked -i /tmp/body.md > /tmp/body.html

  {
    printf '%s' "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>OpenG2P Versions &amp; Change logs</title>"
    printf '%s' "$CSS"
    printf '%s' "</head><body><div class=\"wrap\"><header class=\"site\"><span class=\"t\">&#128230; OpenG2P Versions &amp; Change logs</span><a href=\"${root}index.html\">Home</a></header>"
    cat /tmp/body.html
    printf '%s' "</div></body></html>"
  } > "$out"
  echo "built $out"
done < /tmp/mdlist

echo "done: $(find "$OUT" -name '*.html' | wc -l) pages"
