#!/usr/bin/env sh
#
# Build the change-log static site (no Jekyll -- avoids GitHub-coupled themes).
# Converts every *.md in this repo into public/<path>.html with one branded
# OpenG2P template, rewriting inter-page links (.md / extension-less CHANGELOG
# -> .html). The markdown itself is generated by each repo's CI `changelog` job.
#
# Branding: OpenG2P colours + horizontal logo (assets/openg2p-logo.png).

set -eu

OUT=public
rm -rf "$OUT"; mkdir -p "$OUT"
YEAR=$(date -u +%Y)

# Static assets (logo, etc.) -> served at the site root.
[ -d assets ] && cp -f assets/*.png assets/*.svg "$OUT"/ 2>/dev/null || true

# Markdown -> HTML. marked keeps raw HTML (our <a id> anchors) and GFM tables.
npm install -g marked@12 >/dev/null 2>&1

CSS='<style>
:root{
  --ink:#061327; --yellow:#F5BB1A; --orange:#F07B1A;
  --line:#e6e9ee; --lightgrey:#F6F6F6; --link:#0E63C9; --muted:#5b6472;
}
*{box-sizing:border-box}
body{font-family:Roboto,-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  color:var(--ink);background:#fff;margin:0;line-height:1.62;-webkit-font-smoothing:antialiased}
.wrap{max-width:1040px;margin:0 auto;padding:0 32px}
header.site{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:16px;padding:22px 0 18px;border-bottom:3px solid var(--yellow)}
header.site a.brand{display:inline-flex;align-items:center;text-decoration:none;justify-self:start}
header.site img{display:block;height:36px;width:auto}
header.site .site-title{grid-column:2;text-align:center;color:var(--ink);font-weight:700;font-size:25px;letter-spacing:.01em}
header.site a.home{grid-column:3;justify-self:end;font-weight:600;font-size:15px;white-space:nowrap}
@media (max-width:680px){
  header.site{grid-template-columns:1fr;justify-items:center;gap:8px}
  header.site a.brand{justify-self:center}
  header.site .site-title{grid-column:1;font-size:20px}
  header.site a.home{grid-column:1;justify-self:center}
}
main{padding:8px 0 8px}
h1{font-size:1.95em;margin:.7em 0 .35em;font-weight:700}
h1,h2{padding-bottom:.28em;border-bottom:1px solid var(--line)}
h2{margin-top:2em;font-size:1.42em;font-weight:600}
h3{font-size:1.12em;margin-top:1.5em}
a{color:var(--link);text-decoration:none}
a:hover{text-decoration:underline}
p,li{max-width:78ch}
table{border-collapse:collapse;margin:16px 0;display:block;overflow:auto;font-size:.95em}
th,td{border:1px solid var(--line);padding:8px 14px;text-align:left}
/* Version, Date and Type are short and fixed-shape; keep them on one line so a
   long Notes cell cannot squeeze them into wrapping. Notes takes the slack. */
th:nth-child(-n+3),td:nth-child(-n+3){white-space:nowrap}
th{background:var(--ink);color:#fff;font-weight:600}
tbody tr:nth-child(2n) td{background:var(--lightgrey)}
code{background:var(--lightgrey);border:1px solid var(--line);padding:.14em .42em;border-radius:5px;
  font-size:85%;font-family:"Roboto Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
blockquote{margin:18px 0;padding:12px 18px;background:var(--lightgrey);
  border-left:4px solid var(--yellow);color:var(--muted);border-radius:0 6px 6px 0}
blockquote p{margin:.3em 0}
hr{border:0;height:1px;background:var(--line);margin:30px 0}
ul{padding-left:1.5em}li{margin:.25em 0}
footer.site-foot{margin-top:56px;border-top:1px solid var(--line);padding:22px 0 40px;color:var(--muted);font-size:13px}
footer.site-foot .fine{margin-top:8px;font-size:12px;color:#9aa3af}
footer.site-foot a{color:var(--link)}
</style>'

FAVICON='<link rel="icon" type="image/svg+xml" href="ROOTfavicon.svg">'

# List every markdown file (skip build output / vcs / node_modules).
find . -type f -name '*.md' \
  -not -path './public/*' -not -path './node_modules/*' -not -path './.git/*' \
  | sed 's#^\./##' | sort > /tmp/mdlist

while IFS= read -r md; do
  [ -n "$md" ] || continue
  rel="${md%.md}"
  out="$OUT/${rel}.html"
  mkdir -p "$(dirname "$out")"

  # depth = number of '/' in rel -> "../" prefix so root links resolve.
  depth=$(printf '%s' "$rel" | awk -F/ '{print NF-1}')
  root=""; i=0; while [ "$i" -lt "$depth" ]; do root="../$root"; i=$((i+1)); done

  # strip any leading Jekyll front matter; rewrite links to .html.
  awk 'NR==1&&/^---$/{f=1;next} f&&/^---$/{f=0;next}{print}' "$md" \
    | sed -E 's#\]\(([^)]*/CHANGELOG)\)#](\1.html)#g; s#\]\(([^)]*)\.md\)#](\1.html)#g' > /tmp/body.md
  marked -i /tmp/body.md > /tmp/body.html

  fav=$(printf '%s' "$FAVICON" | sed "s#ROOT#${root}#")
  {
    printf '%s' "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>OpenG2P Versions &amp; Change logs</title>"
    printf '%s' "$fav"
    printf '%s' "$CSS"
    printf '%s' "</head><body><div class=\"wrap\">"
    printf '%s' "<header class=\"site\"><a class=\"brand\" href=\"https://openg2p.org\"><img src=\"${root}openg2p-logo.png\" alt=\"OpenG2P\"></a><span class=\"site-title\">Versions &amp; Change&nbsp;logs</span><a class=\"home\" href=\"${root}index.html\">Home</a></header>"
    printf '%s' "<main>"
    cat /tmp/body.html
    printf '%s' "</main>"
    printf '%s' "<footer class=\"site-foot\"><div>Version history &amp; change logs for <a href=\"https://github.com/OpenG2P\">OpenG2P repositories</a>, generated automatically by CI.</div><div class=\"fine\">&copy; ${YEAR} OpenG2P. All rights reserved.</div></footer>"
    printf '%s' "</div></body></html>"
  } > "$out"
  echo "built $out"
done < /tmp/mdlist

echo "done: $(find "$OUT" -name '*.html' | wc -l) pages"
